### ISSUE TITLE
Split MARTI from www.tripleawarclub.org subdomain

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/tripleawarclub.org#16]
The `www.tripleawarclub.org` subdomain will be shut down at the end of the year.  MARTI (both production and staging) needs to continue to run after that time.  Currently, MARTI is integrated with the `www` subdomain, and therefore must be split so it can continue to run uninterrupted.

The following tasks must be performed to close this issue:

* [x] Create new `dice-staging.tripleawarclub.org` subdomain.
* [x] Extract MARTI staging configuration to a separate configuration file.
* [x] Move MARTI staging source files to new folder under _/usr/share/nginx/html_.
* [x] ~Move MARTI staging log files to new folder under _/usr/share/nginx/html_.~ (see #14)
* [x] Extract MARTI production configuration to a separate configuration file.
* [x] Move MARTI production source files to new folder under _/usr/share/nginx/html_.
* [x] ~Move MARTI production log files to new folder under _/usr/share/nginx/html_.~ (see #14)

**Comment by ssoloff** [comment]
@RoiEXLab Please update the task list, as needed, and then assign this issue back to me.

**Comment by RoiEXLab** [comment]
I added the subdomain.

**Comment by RoiEXLab** [comment]
Unless you meant that I should create the config for it as well

**Comment by ssoloff** [comment]
@RoiEXLab No, just the subdomain.  I think I can extract the configuration myself.  I'll ask for help otherwise. :smile:

**Comment by ssoloff** [comment]
The MARTI staging server is now independent of the `www.tripleawarclub.org` subdomain.

**Comment by ssoloff** [comment]
@RoiEXLab I'm going to submit some PRs to split the MARTI production server from the `www` subdomain.  Moving the production server is a bit different from the staging server because we'll need to preserve the existing files (e.g. _key.dat_) instead of simply deploying a new version of the code.

I just want to make sure I'm not missing anything.  Can you think of anything that would need to be done other than recursively copying _/usr/share/nginx/html/tripleawarclub.org/public\_html/dice/_ to _/usr/share/nginx/html/dice.tripleawarclub.org/public\_html/_?

**Comment by RoiEXLab** [comment]
@ssoloff I don't think there's much more that needs to be done, other than, of course, update the config files as well.
I think all the relevant data is really stored in that directory. This includes all the hardcoded credentials for the DB as well and since all the data is stored in the DB (other than the key) (at least as far as I'm aware of) we really should be just fine.
If you are still unsure I'd recommend skimming through the php files for any hardcoded file paths, but I can't think of anything else

**Comment by ssoloff** [comment]
The MARTI production server is now independent of the `www.tripleawarclub.org` subdomain.

With that, it should be safe to shut down the `www` subdomain at the end of the year.
