### ISSUE TITLE
Disable Nginx configuration for [www.]tripleawarclub.org subdomain

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/tripleawarclub.org#20]
Now that the War Club has been officially shut down, it has been proposed to disable the Nginx configuration for the `www.tripleawarclub.org` and `tripleawarclub.org` subdomains (`dice.tripleawarclub.org` and `dice-staging.tripleawarclub.org` would continue to operate normally until MARTI is shut down).

If the configuration can be disabled, then there is no longer any need for this repo, and we should consider archiving it.  (All MARTI code and configuration is now hosted in the `triplea-game/dice-server` repo.)

@RoiEXLab You postulated in Gitter that there may be a need to keep some minimal configuration to support TLS.  Please elaborate on that in this issue as to whether or not that would invalidate the overall goal of deleting the _triplewarclub.org_ Nginx configuration.

**Comment by RoiEXLab** [comment]
Well the nginx config is supposed to simply redirect to forums.triplea-game.org 
The TLS config is the same as with the MARTI config.
Since this config really isn't supposed to change, we should be fine with removing it from version control

**Comment by ssoloff** [comment]
> Since this config really isn't supposed to change, we should be fine with removing it from version control

Sorry, I then misunderstood what you were proposing in Gitter.  I thought we were considering removing the configuration completely.  If we're simply freezing it, I don't think it's appropriate to archive the repo because it's still "live."

However, in light of shutting down War Club, I guess we can reduce some of the noise in this repo by removing the _tripleawarclub.org_ folder and updating the README to reflect the current state.

**Comment by RoiEXLab** [comment]
I'd be fine with this as well, although I think a gist would be sufficient version control for a single file.

**Comment by ssoloff** [comment]
Presumably we can stop redirecting from `tripleawarclub.org` to `forum.triplea-game.org` at some point in the future?  Like give it a year or something?

For the certificates, it sounds like we have two separate concerns: MARTI and bots.  Is that correct?  If so, can we update the MARTI configurations, as needed, and add a configuration to the `triplea-game/lobby` repo for the bots (presumably that's the most appropriate repo for bot-related stuff)?

**Comment by RoiEXLab** [comment]
The bots do not require a certificate.
TripleA doesn't encrypt connections in general. We're just encrypting passwords lately.

**Comment by RoiEXLab** [comment]
And yes. At some point we can stop redirecting. I'm not sure if the tripleawarclub.org domain expires at some point.
This domain comes with linode, and I haven't seen an expiration date so far.

**Comment by RoiEXLab** [comment]
So if it doesn't expire, we can simply create A/AAAA records to point to forums.triplea-game.org directly and update the config there to treat tripleawarclub.org as an alias.

**Comment by ssoloff** [comment]
@RoiEXLab It looks like we have a plan (or at least a theory for a plan) for how to retire the Nginx server for the `[www.]tripleawarclub.org` subdomains via DNS.  The question is whether to do that now or at some time in the future?  If the former, we can keep this issue open.  If the latter, I'd suggest we ice box it.

**Comment by ssoloff** [comment]
@RoiEXLab Bumping...

**Comment by RoiEXLab** [comment]
@ssoloff I'd be fine with some point in the future.
Given that the server tripleawarclub is hosted on is the same server as the lobby server, and a simple redirect doesn't produce much overhead it shouldn't be a problem to continue it maintaining it this way.

**Comment by ssoloff** [comment]
@RoiEXLab Sounds good.  Closing this issue for now.
