### ISSUE TITLE
Contributor status

### ISSUE THREAD

**Issue by JayArghArgh** [triplea-game/tripleawarclub.org#5]
Hi there,
can I please be listed as a contributor here so I am able to create a project and properly manage the rectification of web bugs.
Thanks
![image](https://cloud.githubusercontent.com/assets/3242587/21083588/60d046f6-c043-11e6-9975-b5220d28209c.png)

**Comment by DanVanAtta** [comment]
Gave you write access. Let me know if there is more that you could use/need.
