### ISSUE TITLE
Link to download TripleA software is not correct

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/tripleawarclub.org#6]
From: https://github.com/triplea-game/triplea/issues/1355

"Just a FYI -- the current link on the website to "Download Triple" from SourceForge is not correct. The current link yields an empty website without any software at all. The correct link should be the following:

http://www.triplea-game.org/"

**Comment by prastle** [comment]
shouldn't all the previous discussion be displayed?

or am i missing something
Pras

**Comment by DanVanAtta** [comment]
Could you clarify the question? I'm going to guess you mean to ask why is this in a new ticket? If that is the question - the answer is because the 'action item' is only one sentence long. Nobody actually really cares about the discussion unless they do. In which case the link is there for you to follow. The important part is that we can quickly read these tickets (issues) and now what needs to be done with seconds of effort.

**Comment by prastle** [comment]
you answered in 1352 1nd here thxs i get ya now.

**Comment by ssoloff** [comment]
I confirmed that the download link on https://www.tripleawarclub.org/ correctly points to http://www.triplea-game.org/download/.  Closing.
